# Generated by Django 3.0 on 2023-08-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0005_worker_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clean_app.Login'),
            preserve_default=False,
        ),
    ]
