# Generated by Django 3.0 on 2023-08-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0007_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clean_app.User'),
            preserve_default=False,
        ),
    ]
