# Generated by Django 3.0 on 2023-08-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0008_complaint_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='qualification',
        ),
        migrations.AddField(
            model_name='worker',
            name='proof',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
