# Generated by Django 3.0 on 2023-08-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0009_auto_20230818_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='proof',
        ),
        migrations.AddField(
            model_name='worker',
            name='qualification',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
