# Generated by Django 3.0 on 2023-08-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0014_notification_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
