# Generated by Django 3.0 on 2023-08-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0015_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycle',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
