# Generated by Django 3.0 on 2023-09-15 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0018_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='CATEGORY',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='clean_app.Worker_category'),
        ),
    ]
