# Generated by Django 3.0 on 2023-09-15 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0020_cart_ordermain_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDERMAIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clean_app.OrderMain')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clean_app.User')),
            ],
        ),
    ]
