# Generated by Django 3.0 on 2023-09-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0022_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accn', models.CharField(max_length=100)),
                ('Acname', models.CharField(max_length=100)),
                ('Ifsc', models.CharField(max_length=100)),
                ('Cvv', models.CharField(max_length=100)),
                ('Balance', models.IntegerField()),
            ],
        ),
    ]
