# Generated by Django 3.0 on 2023-09-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0025_ordermain_recycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermain',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
