# Generated by Django 3.0 on 2023-09-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0026_ordermain_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersub',
            name='USER',
        ),
        migrations.AddField(
            model_name='ordersub',
            name='PRODUCT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clean_app.Product'),
        ),
        migrations.AddField(
            model_name='ordersub',
            name='order_date',
            field=models.IntegerField(default=1),
        ),
    ]
