# Generated by Django 3.0 on 2023-09-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0028_auto_20230916_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
