# Generated by Django 3.0 on 2023-09-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0032_remove_request_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
