# Generated by Django 3.0 on 2023-09-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0033_pickup_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wasterequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clean_app.User')),
                ('WASTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clean_app.Waste')),
            ],
        ),
    ]
