# Generated by Django 3.0 on 2023-09-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0034_wasterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
