# Generated by Django 3.0 on 2023-09-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0035_wasterequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='request',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
