# Generated by Django 3.0 on 2023-09-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0036_auto_20230919_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasterequest',
            name='WASTE',
        ),
        migrations.RemoveField(
            model_name='wasterequest',
            name='request',
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='WORKER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clean_app.Worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='workinfo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
