# Generated by Django 3.0 on 2023-09-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0037_auto_20230919_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wasterequest',
            new_name='Workerrequest',
        ),
    ]
