# Generated by Django 3.0 on 2023-09-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0038_auto_20230919_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='WASTE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clean_app.Waste'),
            preserve_default=False,
        ),
    ]
