# Generated by Django 3.0 on 2023-09-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0039_request_waste'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('User', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clean_app.User')),
                ('WASTEREQUEST', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clean_app.Request')),
            ],
        ),
    ]
