# Generated by Django 3.0 on 2023-09-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0040_wasterequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WasteRequest',
            new_name='WastePayment',
        ),
    ]
