# Generated by Django 3.0 on 2023-09-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0041_auto_20230921_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastepayment',
            old_name='amount',
            new_name='date',
        ),
        migrations.AddField(
            model_name='wastepayment',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
