# Generated by Django 3.0 on 2023-09-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_app', '0042_auto_20230921_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
